language: generic
sudo: required # We give admin right
services: # We indicate to travis to install a copy of docker in our running container
  - docker

before_install: # Commands to be executed before our test are run
  - docker build -t nguyenanht/multi-container-test -f ./client/Dockerfile.dev ./client # By convention, we use the tag  of our repo

script:
  - docker run -e CI=true nguyenanht/multi-container-test npm test

after_success:
  - docker build -t nguyenanht/multi-client ./client
  - docker build -t nguyenanht/multi-nginx ./nginx
  - docker build -t nguyenanht/multi-server ./server
  - docker build -t nguyenanht/multi-worker ./worker
  # log in to the docker CLI with the environement variables setted in travis console
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push tehm to docker hub
  - docker push nguyenanht/multi-client
  - docker push nguyenanht/multi-nginx
  - docker push nguyenanht/multi-server
  - docker push nguyenanht/multi-worker



deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker" # Name application on Elastic beanstalk
  env: "Docker-env" # Name environment on Elastic beanstalk
  bucket_name: "elasticbeanstalk-eu-west-3-120100701306"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
